import DashboardNavbar from "@/components/Sidebar"
import PageContainer from "@/components/PageContainer"

export default function Dashboard(){
    return (
        <PageContainer>
            <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                <p>A</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>e</p>
                <p>Z</p>
                
        </PageContainer>
    )
}